### ISSUE TITLE
Totems occasionally cause world hang when quitting

### ISSUE THREAD

**Issue by Jackiecrazy** [Daripher/Magic-Totems#3]
This is not reliably reproducible, but totems will interfere with proper saving and quitting occasionally. At that point the only way to quit the game is to kill -9 it. I'm currently procuring a thread dump.

**Comment by Jackiecrazy** [comment]
No luck yet. I did get a lot of these though:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffectInstance.m_19555_(net.minecraft.nbt.CompoundTag)" because the return value of "daripher.totems.block.entity.TotemBlockEntity.getEffect()" is null
	at daripher.totems.block.entity.TotemBlockEntity.m_183515_(TotemBlockEntity.java:53) ~[MagicTotems-1.19.2-1.4a.jar%23506!/:1.4a] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:77) ~[client-1.19.2-20220805.130853-srg.jar%23621!/:?]
```

**Comment by Jackiecrazy** [comment]
got it.
```
java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@19.0.2/Native Method)
        - parking to wait for  <0x000000063c5ce910> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@19.0.2/LockSupport.java:269)
        at net.minecraft.util.thread.BlockableEventLoop.m_5667_(minecraft@1.19.2/BlockableEventLoop.java:152)
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(minecraft@1.19.2/BlockableEventLoop.java:142)
        at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(minecraft@1.19.2/ServerChunkCache.java:1262)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.19.2/ServerChunkCache.java:1158)
        at net.minecraft.world.level.Level.m_6522_(minecraft@1.19.2/Level.java:179)
        at net.minecraft.world.level.Level.m_46865_(minecraft@1.19.2/Level.java:2541)
        at net.minecraft.world.level.Level.m_46745_(minecraft@1.19.2/Level.java:2536)
        at net.minecraft.world.level.Level.m_7702_(minecraft@1.19.2/Level.java:507)
        at net.minecraft.world.level.BlockGetter.m_141902_(minecraft@1.19.2/BlockGetter.java:26)
        at net.minecraft.world.level.CommonLevelAccessor.m_141902_(minecraft@1.19.2/CommonLevelAccessor.java:19)
        at daripher.totems.block.entity.TotemTopBlockEntity.getEffect(totemsofpower@1.4a/TotemTopBlockEntity.java:49)
        at daripher.totems.block.entity.TotemTopBlockEntity.m_183515_(totemsofpower@1.4a/TotemTopBlockEntity.java:34)
        at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(minecraft@1.19.2/BlockEntity.java:77)
        at net.minecraft.world.level.block.entity.BlockEntity.m_187480_(minecraft@1.19.2/BlockEntity.java:64)
        at net.minecraft.world.level.chunk.LevelChunk.m_8051_(minecraft@1.19.2/LevelChunk.java:368)
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(minecraft@1.19.2/ChunkSerializer.java:342)
        at net.minecraft.server.level.ChunkMap.m_140258_(minecraft@1.19.2/ChunkMap.java:803)
        at net.minecraft.server.level.ChunkMap.m_202998_(minecraft@1.19.2/ChunkMap.java:497)
        at net.minecraft.server.level.ChunkMap$$Lambda$52007/0x0000000805792678.accept(minecraft@1.19.2/Unknown Source)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@19.0.2/CompletableFuture.java:718)
        at java.util.concurrent.CompletableFuture$Completion.run(java.base@19.0.2/CompletableFuture.java:482)
        at net.minecraft.server.level.ChunkMap.m_140353_(minecraft@1.19.2/ChunkMap.java:470)
        at net.minecraft.server.level.ChunkMap.m_140280_(minecraft@1.19.2/ChunkMap.java:441)
        at net.minecraft.server.level.ServerChunkCache.m_201698_(minecraft@1.19.2/ServerChunkCache.java:314)
        at net.minecraft.server.MinecraftServer.m_7041_(minecraft@1.19.2/MinecraftServer.java:567)
        at net.minecraft.client.server.IntegratedServer.m_7041_(minecraft@1.19.2/IntegratedServer.java:173)
        at net.minecraft.server.MinecraftServer.m_130011_(minecraft@1.19.2/MinecraftServer.java:682)
        at net.minecraft.server.MinecraftServer.m_206580_(minecraft@1.19.2/MinecraftServer.java:244)
        at net.minecraft.server.MinecraftServer$$Lambda$46968/0x00000008051a8230.run(minecraft@1.19.2/Unknown Source)
        at java.lang.Thread.run(java.base@19.0.2/Thread.java:1589)
```
My best guess is that the totem's bottom block check (and maybe top block check as well) should be wrapped in a check to see if the chunk is loaded.

As an aside, I notice that the totems will grant effects on both the client and the server, which, if the server one didn't stick for any reason, leads to a client one that wouldn't go away until reload.
